{% set name = "requests-unixsocket" %}
{% set version = "0.2.0" %}
{% set sha256 = "9e5c1a20afc3cf786197ae59c79bcdb0e7565f218f27df5f891307ee8817c1ea" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - pbr >=1.3,<2

  run:
    - python
    - requests >=2.12,<3
    - urllib3 >=1.16,<2

test:
  imports:
    - requests_unixsocket

about:
  home: https://github.com/msabramo/requests-unixsocket
  license: Apache 2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'Use requests to talk HTTP via a UNIX domain socket'

extra:
  recipe-maintainers:
    - sodre
