travis:
  secure:
    BINSTAR_TOKEN: NcHufnkoiHVGv5fx+qb/5XKltxWuNe5GHzz/fBT3h653w4b2gHuGvH++CYL3aHviubMFdhjwSxQgxcS+gzezWTXRV+9vFFsWZZyq1dqlwY4dhPWDwg4yVWhBQmm+oxC6PelcnhxNZvBBY61M4joNNoIVWkLmyXAVdrGTakwb5DwUMsCcx+ti7PlFkGX0DrDulTwQUd8qCItkQFPajl+bzSCUo9aaR0JGOvaIrtSJx9JP6+03PDhDUGmEAmKBVy1cgO0153/fmqQq/qLabqwDk6UT93XVyAwHmYC/t7RCReUy/WHr3y71J6uSYF1k4t+TLd7C1jJb7XNHTsUBIZ4/v+GsUx7Zxu7qylHP12CNGwiOOp/daV88qI5WsjeqmbEGyEZMGjQ4PSZksardvEXs8ZCyW2Oe0LNcYCQDdGibAC2LCwI49VFNzPeWXfaBwTTfjEYStCDkUWiOwA0toQb1oOpcVCq4geUmaycrKpWeaGZtu8MuNWN+cBddka1b9oD89OEdAeRUZmqHGRms13tEk1xrV+SpGQ72tDqHYgUt0zKXvN9FVc5ZR8h0XzzBXINOfxzFHBmibK2Aypiy/Cq4shux+TXUTec2JUA4auISTrr5EfOA/Y2PQxG06BP/n0L9TXCMvfb71yM9ef2+UsALN39q75P5BlxHiY7fFGdvPYo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
