travis:
  secure:
    BINSTAR_TOKEN: X5mMqEEaLLezrs7E2XNQWdJZFis+LtJS+vx9JapUuP38kSzIFuwLCy/FzjgDJ2/etUqkr3bqdU0tXHrOU/eL+Yf7VcEhSMw41kNq2+aQju9lboKvO8Uxu0ohBq1jfsGVBk8987wFl7UD4/AFBKxom8Tw1Aok1WC0Zxuk476d4SPiy5tkWlA1hjGPQwduEQajev+4zq/3JTwD43CEjimyIky8d/5uUJcyAWH3k/yNVMNe0xGI4TSzxscdoMUS/CkxUBugEWvK+KdoNL7f9YSYP5re7ibaRx1oauPhVqwaF3rxVR4QF/Ud45LtxzpZzeCONb+JZ/6mlQeQKhg1llN5UJhcE2aeVOAccuX/867okz9Lagc2ZTCP/cKct6cmjCg2Wk/gDkkAkCJaVi/rYtpTzg33tcFZUezRP3PxPjJLAccLGZXCcFIlgeeDhr4zDL9flkHt+FYPL/j6wBp6+tgJy5i/AsXkxbchC+msqSMEqFVDueofDmrn7XdSFPZNK7DPAzhOvFZkG/jTNt5o+VH5M2tzg/93xNFs900HrTRCFVchswj5BBUGqWllpoIDlxoeVPXnoWXPiEdWncv0cYuzPt0AhH6rGvG3dzv5XFphF95lM+UDRTH9tGhpup2O3SiQMX6kArsCtphRyPmwm7lNb670unIdaWHk5GyJ/C5zXPU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
